apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pw-manager-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pwManager.storage.size }}
  storageClassName: {{ .Values.pwManager.storage.storageClassName }}
