apiVersion: v1
kind: Service
metadata:
  name: pw-manager
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.pwManager.nodePort }}
      name: http
  selector:
    app: pw-manager
