# nextflow-job.yaml (Nextflow handles git)
apiVersion: batch/v1
kind: Job
metadata:
  name: nextflow-pipeline
  namespace: nf-shard
spec:
  template:
    spec:
      serviceAccountName: nextflow-sa
      containers:
      - name: nextflow
        image: nextflow/nextflow
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: ["nextflow run https://github.com/jvjvjvjv/nextflow-testing.git -profile harmony,shard -r main --num_replicates 2"]
        workingDir: /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        env:
        - name: NXF_WORK
          value: /workspace/work
        - name: NXF_HOME
          value: /workspace/.nextflow
        - name: NXF_K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NXF_K8S_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NXF_K8S_STORAGE_CLAIM_NAME
          value: nextflow-pvc
        - name: NXF_K8S_STORAGE_MOUNT_PATH
          value: /workspace

        # Tower/nf-shard config
        - name: TOWER_ACCESS_TOKEN
          value: "ceb6d7c5a9fc1319-78890f02ed21e136-f09661b80172e6e1-8926bf9c880fefaf"
        - name: TOWER_API_ENDPOINT
          value: "http://nextjs:3000/api"
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: nextflow-pvc
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
