# nextflow-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nextflow-pipeline
  namespace: user1-nfshard
spec:
  template:
    spec:
      serviceAccountName: user1-nfshard-nf-shard
      containers:
      - name: nextflow
        image: registry.rc.umass.edu:5050/harmony/infrastructure/user-resources/nextflow
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: ["nextflow run https://github.com/jvjvjvjv/nextflow-testing.git -profile harmony,shard -r main --num_replicates 2"]
        workingDir: /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        env:
        - name: NXF_WORK
          value: /workspace/work
        - name: NXF_HOME
          value: /workspace/.nextflow
        - name: NXF_K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NXF_K8S_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NXF_K8S_STORAGE_CLAIM_NAME
          value: user1-nfshard-nf-shard-nextflow
        - name: NXF_K8S_STORAGE_MOUNT_PATH
          value: /workspace

        # Tower/nf-shard config
        - name: TOWER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: user1-nfshard-nf-shard-secrets
              key: default-access-token
        - name: TOWER_API_ENDPOINT
          value: "http://user1-nfshard-nf-shard-app:3000/api"
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: user1-nfshard-nf-shard-nextflow
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
