# nextflow-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nextflow-pipeline
  namespace: nextflow
spec:
  template:
    spec:
      serviceAccountName: nextflow-sa-cr
      containers:
      - name: nextflow
        image: registry.rc.umass.edu:5050/harmony/infrastructure/user-resources/nextflow
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: ["nextflow run https://github.com/jvjvjvjv/nextflow-testing.git -profile harmony,shard -r main --num_replicates 2"]
        workingDir: /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        env:
        - name: NXF_WORK
          value: /workspace/work
        - name: NXF_HOME
          value: /workspace/.nextflow
        - name: NXF_K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NXF_K8S_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NXF_K8S_STORAGE_CLAIM_NAME
          value: nextflow-pvc-dynamic
        - name: NXF_K8S_STORAGE_MOUNT_PATH
          value: /workspace

        # Tower/nf-shard config
        - name: TOWER_ACCESS_TOKEN
          value: 0f4f2646-2231-4459-b36d-175f0c307311
        - name: TOWER_API_ENDPOINT
          value: "http://192.168.123.33:3000/api"
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: nextflow-pvc-dynamic
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
