apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres-shared
spec:
  storageClassName: vastdata-vast1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
