apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile all -f docker-compose.yml -n nf-shard
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: nextjs
  name: nextjs
  namespace: nf-shard
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    io.kompose.service: nextjs
