apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    {{- include "nextflow-job.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "nextflow-job.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      # nf-shard sidecar container
      initContainers:
      - name: nf-shard
        image: "{{ .Values.nfShard.image.repository }}:{{ .Values.nfShard.image.tag }}"
        imagePullPolicy: {{ .Values.nfShard.image.pullPolicy }}
        restartPolicy: Always
        ports:
        - containerPort: 3000
          name: shard-port
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /api
            port: 3000
          failureThreshold: {{ .Values.nfShard.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.nfShard.readinessProbe.periodSeconds }}

        env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: app-username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: app-password
        - name: APP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: app-secret-key
        - name: DEFAULT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: default-access-token
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: postgres-uri
        - name: LOG_LEVEL
          value: {{ .Values.nfShard.logLevel | quote }}
        - name: HOSTNAME
          value: "0.0.0.0"

      # Nextflow container
      containers:
      - name: nextflow
        image: "{{ .Values.nextflow.image.repository }}:{{ .Values.nextflow.image.tag }}"
        imagePullPolicy: {{ .Values.nextflow.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - |
{{ .Values.nextflow.runCommand | indent 12 }}

        workingDir: {{ .Values.storage.workspacePath }}
        volumeMounts:
        - name: workspace
          mountPath: {{ .Values.storage.workspacePath }}
        
        env:
        - name: NXF_WORK
          value: {{ .Values.storage.workspacePath }}/work
        - name: NXF_HOME
          value: {{ .Values.storage.workspacePath }}/.nextflow
        - name: NXF_K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NXF_K8S_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NXF_K8S_STORAGE_CLAIM_NAME
          value: {{ .Values.storage.pvcName }}
        - name: NXF_K8S_STORAGE_MOUNT_PATH
          value: {{ .Values.storage.workspacePath }}
        - name: TOWER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: nf-shard-secrets
              key: default-access-token
        - name: TOWER_API_ENDPOINT
          value: "http://localhost:3000/api"

      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: {{ .Values.storage.pvcName }}

      restartPolicy: Never
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}